# Generated by Django 5.1.7 on 2025-03-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('single_vote_per_shareholder', models.BooleanField()),
                ('interest', models.BooleanField()),
                ('question', models.TextField()),
                ('decision', models.TextField()),
                ('cumulative', models.BooleanField()),
                ('seat_count', models.IntegerField()),
            ],
            options={
                'db_table': 'meeting_agenda',
            },
        ),
        migrations.CreateModel(
            name='DjangoRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('registered', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'meeting_django_relation',
            },
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, max_length=200, null=True)),
                ('is_result', models.BooleanField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'meeting_docs',
            },
        ),
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('issuer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=300)),
                ('short_name', models.CharField(max_length=96)),
                ('address', models.CharField(max_length=256)),
                ('zip', models.IntegerField()),
                ('ogrn', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'meeting_issuer',
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('meeting_id', models.IntegerField(primary_key=True, serialize=False)),
                ('meeting_name', models.CharField(blank=True, max_length=100, null=True)),
                ('meeting_location', models.CharField(blank=True, max_length=200, null=True)),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('protocol_date', models.DateField(blank=True, null=True)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('checkin', models.DateTimeField(blank=True, null=True)),
                ('closeout', models.DateTimeField(blank=True, null=True)),
                ('meeting_open', models.DateTimeField(blank=True, null=True)),
                ('meeting_close', models.DateTimeField(blank=True, null=True)),
                ('vote_counting', models.DateTimeField(blank=True, null=True)),
                ('annual_or_unscheduled', models.BooleanField()),
                ('first_or_repeated', models.BooleanField()),
                ('record_date', models.DateField(blank=True, null=True)),
                ('early_registration', models.BooleanField()),
                ('meeting_url', models.CharField(blank=True, max_length=100, null=True)),
                ('inter_or_extra_mural', models.BooleanField()),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meeting_main',
            },
        ),
        migrations.CreateModel(
            name='QuestionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_id', models.IntegerField()),
                ('detail_text', models.TextField()),
            ],
            options={
                'db_table': 'meeting_question_detail',
            },
        ),
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('registrar_id', models.IntegerField(primary_key=True, serialize=False)),
                ('registrar_name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=256)),
                ('zipcode', models.IntegerField()),
                ('ogrn', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'meeting_registrar',
            },
        ),
    ]
