# Generated by Django 5.1.7 on 2025-03-13 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meeting', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLink',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('key', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'meeting_user_link',
            },
        ),
        migrations.AddField(
            model_name='djangorelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='main',
            name='issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='meeting.issuer'),
        ),
        migrations.AddField(
            model_name='docs',
            name='meeting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meeting.main'),
        ),
        migrations.AddField(
            model_name='djangorelation',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='meeting.main'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='meeting.main'),
        ),
        migrations.AddField(
            model_name='questiondetail',
            name='meeting_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.main'),
        ),
        migrations.AddField(
            model_name='questiondetail',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.agenda'),
        ),
        migrations.AddField(
            model_name='main',
            name='registrar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='meeting.registrar'),
        ),
        migrations.CreateModel(
            name='VoteCount',
            fields=[
                ('vote_count_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_id', models.IntegerField()),
                ('account_fullname', models.CharField(max_length=300)),
                ('json_quantity', models.JSONField(blank=True, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='meeting.main')),
            ],
            options={
                'db_table': 'meeting_vote_count',
                'unique_together': {('meeting', 'account_id')},
            },
        ),
        migrations.AddField(
            model_name='djangorelation',
            name='vote_count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='meeting.votecount'),
        ),
        migrations.CreateModel(
            name='VotingResult',
            fields=[
                ('voting_result_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_id', models.IntegerField()),
                ('json_result', models.JSONField(blank=True, null=True)),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.main')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meeting_voting_result',
                'unique_together': {('meeting_id', 'account_id', 'user_id')},
            },
        ),
        migrations.AddField(
            model_name='djangorelation',
            name='voting_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='meeting.votingresult'),
        ),
        migrations.AlterUniqueTogether(
            name='docs',
            unique_together={('meeting', 'id')},
        ),
        migrations.AlterUniqueTogether(
            name='agenda',
            unique_together={('meeting', 'question_id')},
        ),
        migrations.AlterUniqueTogether(
            name='questiondetail',
            unique_together={('meeting_id', 'question_id', 'detail_id')},
        ),
        migrations.AlterUniqueTogether(
            name='djangorelation',
            unique_together={('meeting', 'account_id', 'user')},
        ),
    ]
