# Generated by Django 5.1.7 on 2025-03-14 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangorelation',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.main'),
        ),
        migrations.AlterField(
            model_name='djangorelation',
            name='registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='djangorelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='djangorelation',
            name='vote_count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.votecount'),
        ),
        migrations.AlterField(
            model_name='djangorelation',
            name='voting_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.votingresult'),
        ),
        migrations.AlterField(
            model_name='docs',
            name='is_result',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='docs',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.main'),
        ),
        migrations.AlterField(
            model_name='main',
            name='meeting_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userlink',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='votecount',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.main'),
        ),
    ]
