# Generated by Django 5.1.7 on 2025-03-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_alter_djangorelation_meeting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='early_registration',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='first_or_repeated',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
