# Generated by Django 5.1.7 on 2025-03-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_alter_main_early_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='interest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='single_vote_per_shareholder',
            field=models.BooleanField(default=False),
        ),
    ]
