# Generated by Django 5.1.7 on 2025-03-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_alter_agenda_interest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiondetail',
            name='id',
        ),
        migrations.AlterField(
            model_name='questiondetail',
            name='detail_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
