# Generated by Django 5.1.7 on 2025-03-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0007_alter_questiondetail_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuer',
            name='issuer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registrar',
            name='registrar_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
