# Generated by Django 5.1.7 on 2025-03-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0008_alter_issuer_issuer_id_alter_registrar_registrar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='status',
            field=models.IntegerField(blank=True, choices=[('expected', 'Ожидается'), ('register', 'Разрешена регистрация'), ('voting', 'Разрешена голосование'), ('end_voting', 'Голосование завершено'), ('end_meeting', 'Собрание завершилось')], default='expected', null=True),
        ),
    ]
