# Generated by Django 5.1.7 on 2025-03-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0011_alter_main_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questiondetail',
            old_name='meeting_id',
            new_name='meeting',
        ),
        migrations.RenameField(
            model_name='questiondetail',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='votingresult',
            old_name='meeting_id',
            new_name='meeting',
        ),
        migrations.RenameField(
            model_name='votingresult',
            old_name='user_id',
            new_name='user',
        ),
    ]
