# Generated by Django 5.1.7 on 2025-03-20 07:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0012_rename_meeting_id_questiondetail_meeting_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='questiondetail',
            old_name='meeting',
            new_name='meeting_id',
        ),
        migrations.RenameField(
            model_name='questiondetail',
            old_name='question',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='votingresult',
            old_name='meeting',
            new_name='meeting_id',
        ),
        migrations.RenameField(
            model_name='votingresult',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='main',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='questiondetail',
            unique_together={('meeting_id', 'question_id', 'detail_id')},
        ),
        migrations.AlterUniqueTogether(
            name='votingresult',
            unique_together={('meeting_id', 'account_id', 'user_id')},
        ),
    ]
