# Generated by Django 5.1.7 on 2025-03-20 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0013_rename_meeting_questiondetail_meeting_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='created_at',
            field=models.DateField(auto_now_add=True, default='2025-03-20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='main',
            name='sent_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Ожидается'), (2, 'Разрешена регистрация'), (3, 'Разрешено голосование'), (4, 'Голосование завершено'), (5, 'Собрание завершилось')], default='1', null=True),
        ),
    ]
