# Generated by Django 5.1.7 on 2025-03-26 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0014_main_created_at_main_created_by_main_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiondetail',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='meeting.agenda'),
        ),
    ]
